name: terraform

on:
  pull_request:
    paths:
      - "infra/terraform/**"
  push:
    branches: [main]
    paths:
      - "infra/terraform/**"

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      TF_VAR_project_name: ${{ github.event.repository.name }}
      TF_VAR_github_repository: ${{ github.repository }}
      TF_VAR_location: eastus
      TF_VAR_environment: demo
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v4
    #
    #   - name: Setup Terraform
    #     uses: hashicorp/setup-terraform@v3
    #     with:
    #       terraform_version: 1.7.5
    #
    #   - name: Azure Login
    #     uses: azure/login@v2
    #     with:
    #       creds: ${{ secrets.AZURE_CREDENTIALS }}
    #
    #   - name: Terraform Init
    #     working-directory: infra/terraform
    #     run: terraform init
    #
    #   - name: Terraform Validate
    #     working-directory: infra/terraform
    #     run: terraform validate
    #
    #   - name: Terraform Plan
    #     working-directory: infra/terraform
    #     run: terraform plan -input=false
